// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(SkuciSeDBContext))]
    [Migration("20211024160004_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("WebAPI.Models.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1u,
                            DateCreated = new DateTime(2021, 10, 24, 18, 0, 3, 699, DateTimeKind.Local).AddTicks(3224),
                            Email = "test@mail.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "test",
                            Username = "test"
                        },
                        new
                        {
                            Id = 2u,
                            DateCreated = new DateTime(2021, 10, 24, 18, 0, 3, 702, DateTimeKind.Local).AddTicks(3208),
                            Email = "test2@mail.com",
                            FirstName = "Jack",
                            LastName = "Daniels",
                            Password = "test2",
                            Username = "test2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
